language: node_js
node_js:
- "stable"

notifications:
  email: false
  slack: andela:kIVwwrSGn5fYVXxtkjD53dav

before_install:
  - psql -c 'drop database if exists hatitest;' -U postgres
  - psql -c 'create database hatitest;' -U postgres
  - NODE_ENV=test npm run migrate

services:
  - postgresql

script:
  - npm test

after_success:
  - npm run coveralls

addons:
  postgresql: "9.3"
