language: node_js
node_js:
- stable
cache: false
notifications:
  email: false
before_install:
  - npm install codecov
  - psql -c 'drop database if exists hatidev;' -U postgres
  - psql -c 'create database hatidev;' -U postgres
services:
  - postgresql
script:
  - npm test
after_success:
  - codecov
addons:
  postgresql: "9.3"
