language: node_js
node_js:
- stable
cache: false
notifications:
  email: false
  slack: andela:kIVwwrSGn5fYVXxtkjD53dav
before_install:
  - psql -c 'drop database if exists hatidev;' -U postgres
  - psql -c 'create database hatidev;' -U postgres
services:
  - postgresql
script:
  - npm test
after_success:
  - npm install codacy-coverage
  - npm run coveralls
addons:
  postgresql: "9.3"
