language: node_js
node_js:
- "stable"

notifications:
  email: false
  slack: andela:kIVwwrSGn5fYVXxtkjD53dav

before_install:
  - npm install -g codeclimate-test-reporter
  - psql -c 'drop database if exists hatidev;' -U jackie
  - psql -c 'create database hatidev;' -U jackie

services:
  - postgresql

script:
  - npm test

after_success:
  - npm run coveralls

addons:
  postgresql: "9.3"
