// Auth
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// Documents
export const CLOSE_DOCUMENT = 'CLOSE_DOCUMENT';

export const DOCUMENTS_REQUEST = 'DOCUMENTS_REQUEST';
export const DOCUMENTS_SUCCESS = 'DOCUMENTS_SUCCESS';
export const DOCUMENTS_FAILURE = 'DOCUMENTS_FAILURE';

export const DOCUMENTS_ADD_REQUEST = 'DOCUMENTS_ADD_REQUEST';
export const DOCUMENTS_ADD_SUCCESS = 'DOCUMENTS_ADD_SUCCESS';
export const DOCUMENTS_ADD_FAILURE = 'DOCUMENTS_ADD_FAILURE';

export const DOCUMENTS_GET_REQUEST = 'DOCUMENT_GET_REQUEST';
export const DOCUMENTS_GET_SUCCESS = 'DOCUMENT_GET_SUCCESS';
export const DOCUMENTS_GET_FAILURE = 'DOCUMENT_GET_FAILURE';

export const DOCUMENTS_UPDATE_REQUEST = 'DOCUMENT_UPDATE_REQUEST';
export const DOCUMENTS_UPDATE_SUCCESS = 'DOCUMENT_UPDATE_SUCCESS';
export const DOCUMENTS_UPDATE_FAILURE = 'DOCUMENT_UPDATE_FAILURE';

export const DOCUMENTS_DELETE_REQUEST = 'DOCUMENT_DELETE_REQUEST';
export const DOCUMENTS_DELETE_SUCCESS = 'DOCUMENT_DELETE_SUCCESS';
export const DOCUMENTS_DELETE_FAILURE = 'DOCUMENT_DELETE_FAILURE';

export const SET_DOCUMENTS_SEARCH_FILTER = 'SET_DOCUMENTS_SEARCH_FILTER';
export const SET_DOCUMENTS_ACCESS_FILTER = 'SET_DOCUMENTS_ACCESS_FILTER';

// Users
export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_FAILURE = 'USER_GET_FAILURE';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';

export const USER_DOCUMENTS_REQUEST = 'USER_DOCUMENTS_REQUEST';
export const USER_DOCUMENTS_SUCCESS = 'USER_DOCUMENTS_SUCCESS';
export const USER_DOCUMENTS_FAILURE = 'USER_DOCUMENTS_FAILURE';

// Roles
export const ROLE_GET_REQUEST = 'ROLE_GET_REQUEST';
export const ROLE_GET_SUCCESS = 'ROLE_GET_SUCCESS';
export const ROLE_GET_FAILURE = 'ROLE_GET_FAILURE';
